PipelineSecrets: {}
cleanup:
  Annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --cleanup
controllerbuild: {}
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  Args:
  - --v
  - 4
  config:
    domain: production.melita.it
    exposer: Ingress
    http: "true"
jenkins:
  Servers:
    Global: {}
prow: {}
amdocs-ws-api:
  replicaCount: 3
  springBoot:
    profiles: default,gcp,ita-production
payment-service-api:
  env:
    STATUS_URL: https://www.melita.it/api/payment/apco/checkout/callback
  springBoot:
    databaseInstance: melita-italy:europe-west3:prod-mysql=tcp:3306
